export const topDealUsers = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    username: "Elva McDonald",
    email: "elva@gmail.com",
    amount: "3.668",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Linnie Nelson",
    email: "linnie@gmail.com",
    amount: "3.256",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Brent Reeves",
    email: "brent@gmail.com",
    amount: "2.998",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Adeline Watson",
    email: "adeline@gmail.com",
    amount: "2.512",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Juan Harrington",
    email: "juan@gmail.com",
    amount: "2.134",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Augusta McGee",
    email: "augusta@gmail.com",
    amount: "1.932",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Angel Thomas",
    email: "angel@gmail.com",
    amount: "1.560",
  },
];
export const chartBoxUser = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title: "Total Users",
  number: "11.238",
  dataKey: "users",
  percentage: 45,
  chartData: [
    { name: "Sun", users: 400 },
    { name: "Mon", users: 600 },
    { name: "Tue", users: 500 },
    { name: "Wed", users: 700 },
    { name: "Thu", users: 400 },
    { name: "Fri", users: 500 },
    { name: "Sat", users: 450 },
  ],
};
export const chartBoxProduct = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title: "Total Products",
  number: "238",
  dataKey: "products",
  percentage: 21,
  chartData: [
    { name: "Sun", products: 400 },
    { name: "Mon", products: 600 },
    { name: "Tue", products: 500 },
    { name: "Wed", products: 700 },
    { name: "Thu", products: 400 },
    { name: "Fri", products: 500 },
    { name: "Sat", products: 450 },
  ],
};
export const chartBoxRevenue = {
  color: "teal",
  icon: "/revenueIcon.svg",
  title: "Total Revenue",
  number: "$56.432",
  dataKey: "revenue",
  percentage: -12,
  chartData: [
    { name: "Sun", revenue: 400 },
    { name: "Mon", revenue: 600 },
    { name: "Tue", revenue: 500 },
    { name: "Wed", revenue: 700 },
    { name: "Thu", revenue: 400 },
    { name: "Fri", revenue: 500 },
    { name: "Sat", revenue: 450 },
  ],
};
export const chartBoxConversion = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title: "Total Ratio",
  number: "2.6",
  dataKey: "ratio",
  percentage: 12,
  chartData: [
    { name: "Sun", ratio: 400 },
    { name: "Mon", ratio: 600 },
    { name: "Tue", ratio: 500 },
    { name: "Wed", ratio: 700 },
    { name: "Thu", ratio: 400 },
    { name: "Fri", ratio: 500 },
    { name: "Sat", ratio: 450 },
  ],
};
export const barChartBoxRevenue = {
  title: "Profit Earned",
  color: "#8884d8",
  dataKey: "profit",
  chartData: [
    {
      name: "Sun",
      profit: 4000,
    },
    {
      name: "Mon",
      profit: 3000,
    },
    {
      name: "Tue",
      profit: 2000,
    },
    {
      name: "Wed",
      profit: 2780,
    },
    {
      name: "Thu",
      profit: 1890,
    },
    {
      name: "Fri",
      profit: 2390,
    },
    {
      name: "Sat",
      profit: 3490,
    },
  ],
};
export const barChartBoxVisit = {
  title: "Total Visit",
  color: "#FF8042",
  dataKey: "visit",
  chartData: [
    {
      name: "Sun",
      visit: 4000,
    },
    {
      name: "Mon",
      visit: 3000,
    },
    {
      name: "Tue",
      visit: 2000,
    },
    {
      name: "Wed",
      visit: 2780,
    },
    {
      name: "Thu",
      visit: 1890,
    },
    {
      name: "Fri",
      visit: 2390,
    },
    {
      name: "Sat",
      visit: 3490,
    },
  ],
};
export const userRows = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Hubbard",
    firstName: "Eula",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Manning",
    firstName: "Stella",
    email: "comhuhmit@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Greer",
    firstName: "Mary",
    email: "ujudokon@hottmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Williamson",
    firstName: "Mildred",
    email: "tinhavabe@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Gross",
    firstName: "Jose",
    email: "gobtagbes@yahoo.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Sharp",
    firstName: "Jeremy",
    email: "vulca.eder@mail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Lowe",
    firstName: "Christina",
    email: "reso.bilic@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Dean",
    firstName: "Garrett",
    email: "codaic@mail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Parsons",
    firstName: "Leah",
    email: "uzozor@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Reid",
    firstName: "Elnora",
    email: "tuhkabapu@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Dunn",
    firstName: "Gertrude",
    email: "gibo@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Williams",
    firstName: "Mark",
    email: "tic.harvey@hotmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/761977/pexels-photo-761977.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Cruz",
    firstName: "Charlotte",
    email: "ceuc@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Harper",
    firstName: "Sara",
    email: "bafuv@hotmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Griffin",
    firstName: "Eric",
    email: "ubi@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
];
export const rooms = [
  {
    id: 1,
    roomNumber: "101",
    name: "John Doe",
    details: "Standard Single Room",
    phoneNumber: "123-456-7890",
    status: "Occupied",
  },
  {
    id: 2,
    roomNumber: "102",
    name: "Jane Smith",
    details: "Deluxe Double Room",
    phoneNumber: "987-654-3210",
    status: "Vacant",
  },
  {
    id: 3,
    roomNumber: "103",
    name: "Michael Johnson",
    details: "Executive Suite",
    phoneNumber: "555-123-4567",
    status: "Occupied",
  },
  {
    id: 4,
    roomNumber: "104",
    name: "Emily Williams",
    details: "Family Room",
    phoneNumber: "777-888-9999",
    status: "Maintenance",
  },
  {
    id: 5,
    roomNumber: "105",
    name: "David Brown",
    details: "Standard Twin Room",
    phoneNumber: "222-333-4444",
    status: "Vacant",
  },
  {
    id: 6,
    roomNumber: "106",
    name: "Sarah Davis",
    details: "Deluxe King Room",
    phoneNumber: "666-777-8888",
    status: "Occupied",
  },
  {
    id: 7,
    roomNumber: "107",
    name: "Christopher Wilson",
    details: "Junior Suite",
    phoneNumber: "444-555-6666",
    status: "Vacant",
  },
  {
    id: 8,
    roomNumber: "108",
    name: "Olivia Johnson",
    details: "Standard Queen Room",
    phoneNumber: "111-222-3333",
    status: "Occupied",
  },
  {
    id: 9,
    roomNumber: "109",
    name: "William Martin",
    details: "Penthouse Suite",
    phoneNumber: "888-999-0000",
    status: "Vacant",
  },
  {
    id: 10,
    roomNumber: "110",
    name: "Sophia Anderson",
    details: "Presidential Suite",
    phoneNumber: "333-444-5555",
    status: "Occupied",
  },
];
export const electricity = [
  {
    id: 1,
    roomNumber: "101",
    status: "Occupied",
    previousMeter: 1200,
    currentMeter: 1450,
    consumptionDifference: 250,
  },
  {
    id: 2,
    roomNumber: "102",
    status: "Vacant",
    previousMeter: 1800,
    currentMeter: 1900,
    consumptionDifference: 100,
  },
  {
    id: 3,
    roomNumber: "103",
    status: "Occupied",
    previousMeter: 2200,
    currentMeter: 2400,
    consumptionDifference: 200,
  },
  {
    id: 4,
    roomNumber: "104",
    status: "Maintenance",
    previousMeter: 1500,
    currentMeter: 1550,
    consumptionDifference: 50,
  },
  {
    id: 5,
    roomNumber: "105",
    status: "Vacant",
    previousMeter: 800,
    currentMeter: 900,
    consumptionDifference: 100,
  },
  {
    id: 6,
    roomNumber: "106",
    status: "Occupied",
    previousMeter: 3500,
    currentMeter: 3700,
    consumptionDifference: 200,
  },
  {
    id: 7,
    roomNumber: "107",
    status: "Vacant",
    previousMeter: 2800,
    currentMeter: 2900,
    consumptionDifference: 100,
  },
  {
    id: 8,
    roomNumber: "108",
    status: "Occupied",
    previousMeter: 900,
    currentMeter: 950,
    consumptionDifference: 50,
  },
  {
    id: 9,
    roomNumber: "109",
    status: "Vacant",
    previousMeter: 4100,
    currentMeter: 4200,
    consumptionDifference: 100,
  },
  {
    id: 10,
    roomNumber: "110",
    status: "Occupied",
    previousMeter: 600,
    currentMeter: 750,
    consumptionDifference: 150,
  },
];
export const bill = [
  {
    id: 1,
    roomNumber: "101",
    fullName: "John Doe",
    email: "john@example.com",
    status: "Not Sent",
  },
  {
    id: 2,
    roomNumber: "102",
    fullName: "Jane Smith",
    email: "jane@example.com",
    status: "Sent",
  },
  {
    id: 3,
    roomNumber: "103",
    fullName: "Michael Johnson",
    email: "michael@example.com",
    status: "Not Sent",
  },
  {
    id: 4,
    roomNumber: "104",
    fullName: "Emily Williams",
    email: "emily@example.com",
    status: "Sent",
  },
  {
    id: 5,
    roomNumber: "105",
    fullName: "David Brown",
    email: "david@example.com",
    status: "Not Sent",
  },
  {
    id: 6,
    roomNumber: "106",
    fullName: "Sophia Martinez",
    email: "sophia@example.com",
    status: "Sent",
  },
  {
    id: 7,
    roomNumber: "107",
    fullName: "James Anderson",
    email: "james@example.com",
    status: "Not Sent",
  },
  {
    id: 8,
    roomNumber: "108",
    fullName: "Olivia Taylor",
    email: "olivia@example.com",
    status: "Sent",
  },
  {
    id: 9,
    roomNumber: "109",
    fullName: "William Hernandez",
    email: "william@example.com",
    status: "Not Sent",
  },
  {
    id: 10,
    roomNumber: "110",
    fullName: "Ava Lopez",
    email: "ava@example.com",
    status: "Sent",
  },
  {
    id: 11,
    roomNumber: "111",
    fullName: "Liam Garcia",
    email: "liam@example.com",
    status: "Not Sent",
  },
];
export const paybill = [
  {
    id: 1,
    roomNumber: "101",
    fullName: "John Doe",
    email: "john@example.com",
    status: "Pending",
  },
  {
    id: 2,
    roomNumber: "102",
    fullName: "Jane Smith",
    email: "jane@example.com",
    status: "Paid",
  },
  {
    id: 3,
    roomNumber: "103",
    fullName: "Michael Johnson",
    email: "michael@example.com",
    status: "Pending",
  },
  {
    id: 4,
    roomNumber: "104",
    fullName: "Emily Williams",
    email: "emily@example.com",
    status: "Paid",
  },
  {
    id: 5,
    roomNumber: "105",
    fullName: "David Brown",
    email: "david@example.com",
    status: "Pending",
  },
  {
    id: 6,
    roomNumber: "106",
    fullName: "Olivia Martinez",
    email: "olivia@example.com",
    status: "Paid",
  },
  {
    id: 7,
    roomNumber: "107",
    fullName: "James Miller",
    email: "james@example.com",
    status: "Pending",
  },
  {
    id: 8,
    roomNumber: "108",
    fullName: "Sophia Wilson",
    email: "sophia@example.com",
    status: "Paid",
  },
  {
    id: 9,
    roomNumber: "109",
    fullName: "William Taylor",
    email: "william@example.com",
    status: "Pending",
  },
  {
    id: 10,
    roomNumber: "110",
    fullName: "Ava Anderson",
    email: "ava@example.com",
    status: "Paid",
  },
];

